cask "ghostty"
tap "dashlane/tap"
tap "weihanglo/sfz", "https://github.com/weihanglo/sfz.git"
brew "coreutils"
brew "fzf"
brew "httpie"
brew "jq"
brew "yq"
brew "lazygit"
brew "neovim"
brew "parallel"
brew "python@3.11"
brew "ripgrep"
brew "starship"
brew "stow"
brew "stylua"
