#!/bin/bash

# Homebrew
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash

    if [[ $(uname) == "Darwin" ]]; then
        # TODO: source brew to shell env for osx
    else
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    fi
else
    echo "Homebrew is already installed"
fi


# Brewfile
if [ -f "Brewfile" ]; then
    echo "Installing packages from Brewfile..."

    if [[ $(uname) == "Darwin" ]]; then
        brew bundle
    else
        brew bundle --no-cask
    fi
else
    echo "Brewfile not found. Skipping package installation."
fi

source ~/.zshrc

# Stow
stow -R -v -t ~ -d ~/dev/dotfiles/home .

source ~/.zshrc

# Votla
if ! command -v volta &> /dev/null; then
    echo "Installing Volta..."
    curl https://get.volta.sh | bash
else
    echo "Volta is already installed"
fi

# Node
if ! command -v node &> /dev/null; then
    volta install node
fi

# pnpm
if ! command -v pnpm &> /dev/null; then
    volta install pnpm
fi
