#!/bin/bash

# Homebrew
if ! command -v brew &> /dev/null; then
    echo "Installing Homebrew..."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
else
    echo "Homebrew is already installed"
fi

# Brewfile
if [ -f "Brewfile" ]; then
    echo "Installing packages from Brewfile..."
    brew bundle
else
    echo "Brewfile not found. Skipping package installation."
fi

# Stow
stow -R -v -t ~ -d ~/dev/dotfiles/home .

source ~/.zshrc

# Votla
if ! command -v volta &> /dev/null; then
    echo "Installing Volta..."
    curl https://get.volta.sh | bash
else
    echo "Volta is already installed"
fi

# Node
volta install node

# Pnpm
volta install pnpm