os:
  editPreset: "nvim"
git:
  paging:
    pager: delta --dark --paging=never
notARepository: skip
customCommands:
  - key: "b"
    command: "gh browse"
    context: "files"
  - key: "b"
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
