gui:
  nerdFontsVersion: "3"
os:
  editPreset: "nvim"
git:
  log:
    showGraph: always
notARepository: skip
customCommands:
  - key: "b"
    command: "gh browse"
    context: "files"
  - key: "b"
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
