return {
  -- treesitter syntax highlighting
  -- See: https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages
  treesitter_langs = {
    'bash',
    'diff',
    'elixir',
    'html',
    'lua',
    'luadoc',
    'markdown',
    'rust',
    'tsx',
    'javascript',
    'typescript',
    'graphql',
    'dockerfile',
    'json',
    'sql',
    'toml',
    'prisma',
    'proto',
    'python',
    'vim',
    'vimdoc',
    'yaml',
  },
  -- language servers (per-server config lives in after/lsp/*.lua)
  -- See: https://github.com/mason-org/mason-lspconfig.nvim?tab=readme-ov-file#available-lsp-servers
  servers = {
    'lua_ls',
    'rust_analyzer',
    'elixirls',
    'graphql',
    'html',
    'prismals',
    'pyright',
    'eslint',
    'sqlls',
    'tailwindcss',
    'dockerls',
    'jsonls',
    'yamlls',
    'taplo',
    'biome',
  },
}
